- CHANGELOG.md
- cloudformation.yaml
> Issue 3.dockter.2

- CHANGELOG.md
- cloudformation.yaml
> Issue 3.dockter.3

- CHANGELOG.md
> #3 Updated

- cloudformation.yaml
> #12 email HTML updates

- cloudformation.yaml
> #11 added redrive policy to redoer input queue

- cloudformation.yaml
> #15 Fix sshd-max Family:

- cloudformation.yaml
> #20 updated EFS wait lambda

- cloudformation.yaml
> #20 added wait for EFS to be ready

- cloudformation.yaml
> #4 lower cased coginito user pool domain

- cloudformation.yaml
> 25 updated cognito admin email

- cloudformation.yaml
> 27 lower cased load balancer URL

- cloudformation.yaml
> #29 removed private subnet from sshd services

- cloudformation.yaml
> #31 update memory for key services

- cloudformation.yaml
> #31 updated cpu for key services

- cloudformation.yaml
> #34 removed database initialization

- cloudformation.yaml
> #40 updated to support required CIDR inbound block

- cloudformation.yaml
Issue number: #42 and #43
???
???
> Issue 42.ron.0

- cloudformation.yaml
> #48 removed swagger ui from being installed with basic

- .gitignore
- docs/README.md
> Issue 45.dockter.1

- cloudformation.yaml
> #51 conditionally display email stanzas

- README.md
- cloudformation.yaml
- docs/README.md
> Issue 52.ron.0

- cloudformation.yaml
> #41 updated to the new POC server

- cloudformation.yaml
Issue number: #35 
Need to specific the resources used by the CFT to meet AWS marketplace standards
> Issue 35.chia.1

- cloudformation.yaml
> #57 updated web app environment vars

- cloudformation.yaml
> #67 updated api server role

- cloudformation.yaml
> #69 updated xterm version

- cloudformation.yaml
> Issue 71.ron.0

- cloudformation.yaml
> #74 udpated parameter list order to match marketplace

- cloudformation.yaml
> #73 updated with all the latest images versions

- CHANGELOG.md
- cloudformation.yaml
> #77 updated change log and version number

- cloudformation.yaml
> #79 added SENZING_ENGINE_CONFIGURATION_JSON

- CHANGELOG.md
- cloudformation.yaml
> #93 updates completed

- .github/workflows/copy-to-s3.yaml
Issue number: #95 
It was going to the wrong bucket
> copy cloudformation.yaml to the correct bucket

- cloudformation.yaml
> #37 removed flow logs

- .github/workflows/copy-to-s3.yaml
Issue number: #97 
cloudformation files copied to s3 also need to be public
> Making files copied up to S3 on release public

- cloudformation.yaml
> Issue 100.ron.0

- CHANGELOG.md
- cloudformation.yaml
> #102 updated yum container version

- CHANGELOG.md
- cloudformation.yaml
> Issue 104.ron.0

- CHANGELOG.md
- cloudformation.yaml
> #106 updated image versions

- CONTRIBUTING.md
- README.md
- cloudformation.yaml
- cloudformationV2.yaml
- docs/README.md
> #111 Migrate from master to main

- README.md
> Issue 114.ron.0

- README.md
> #117 updated readme

- CHANGELOG.md
- README.md
- cloudformation.yaml
> #119 updated resource names

- README.md
> #121 updated readme

- CHANGELOG.md
- cloudformation.yaml
> Issue 133.ron.0

- CHANGELOG.md
- cloudformation.yaml
Issue number: #136 #132 #128
???
???
> Issue 136.ron.0

- CHANGELOG.md
- cloudformation.yaml
> Issue 130.ron.0

- CHANGELOG.md
- cloudformation.yaml
> #144 updated senzing version

- CHANGELOG.md
- cloudformation.yaml
> #146 updated image versions

- CHANGELOG.md
- cloudformation.yaml
> #147 removed redo queues

- .github/CODEOWNERS
- .github/workflows/copy-to-s3.yaml
> #157 Change secrets variable names

- README.md
- docs/README.md
> #159 Update links

- CHANGELOG.md
- cloudformation.yaml
> #161 updated docker images, change log and versioning release

- CHANGELOG.md
- cloudformation.yaml
> #165 updated senzing and docker image versions

- CHANGELOG.md
- cloudformation.yaml
> #167 update docker images and senzing version

- .github/linters/.yaml-lint.yml
- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-garage-dependabot.yaml
- .github/workflows/add-to-project-garage.yaml
- .github/workflows/copy-to-s3.yaml
- .github/workflows/dependabot-approve-and-merge.yaml
- .github/workflows/lint-workflows.yaml
Issue number: senzing-factory/build-resources#69
> senzing-factory/build-resources#69 add linting
